/*
 RequireJS 1.0.1 Copyright (c) 2010-2011, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
(function(){var e=Math,f=/webkit/i.test(navigator.appVersion)?"webkit":/firefox/i.test(navigator.userAgent)?"Moz":"opera"in window?"O":"",j="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,g="ontouchstart"in window,m=f+"Transform"in document.documentElement.style,a=/iphone|ipad/gi.test(navigator.appVersion),k=/playbook/gi.test(navigator.appVersion),c=a||k,q=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||
window.msRequestAnimationFrame||function(b){return setTimeout(b,17)}}(),n=window.cancelRequestAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,d="onorientationchange"in window?"orientationchange":"resize",i=g?"touchstart":"mousedown",t=g?"touchmove":"mousemove",r=g?"touchend":"mouseup",v=g?"touchcancel":"mouseup",B="translate"+(j?"3d(":"("),s=j?",0)":")",j=function(b,
h){var p;this.wrapper="object"==typeof b?b:document.getElementById(b);this.wrapper.style.overflow="hidden";this.scroller=this.wrapper.children[0];this.options={hScroll:!0,vScroll:!0,x:0,y:0,bounce:!0,bounceLock:!1,momentum:!0,lockDirection:!0,useTransform:!0,useTransition:!1,onRefresh:null,onBeforeScrollStart:function(b){b.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null};for(p in h)this.options[p]=
h[p];this.x=this.options.x;this.y=this.options.y;this.options.useTransform=m?this.options.useTransform:!1;this.options.hScrollbar=this.options.hScroll&&this.options.hScrollbar;this.options.vScrollbar=this.options.vScroll&&this.options.vScrollbar;this.options.useTransition=c&&this.options.useTransition;this.scroller.style[f+"TransitionProperty"]=this.options.useTransform?"-"+f.toLowerCase()+"-transform":"top left";this.scroller.style[f+"TransitionDuration"]="0";this.scroller.style[f+"TransformOrigin"]=
"0 0";this.options.useTransition&&(this.scroller.style[f+"TransitionTimingFunction"]="cubic-bezier(0.33,0.66,0.66,1)");this.options.useTransform?this.scroller.style[f+"Transform"]=B+this.x+"px,"+this.y+"px"+s:this.scroller.style.cssText+=";position:absolute;top:"+this.y+"px;left:"+this.x+"px";this.refresh();this._bind(d,window);this._bind(i);g||this._bind("mouseout",this.wrapper)};j.prototype={enabled:!0,x:0,y:0,steps:[],scale:1,handleEvent:function(b){switch(b.type){case i:if(!g&&0!==b.button)break;
this._start(b);break;case t:this._move(b);break;case r:case v:this._end(b);break;case d:this._resize();break;case "mouseout":this._mouseout(b);break;case "webkitTransitionEnd":this._transitionEnd(b)}},_resize:function(){this.refresh()},_pos:function(b,h){b=this.hScroll?b:0;h=this.vScroll?h:0;this.options.useTransform?this.scroller.style[f+"Transform"]=B+b+"px,"+h+"px"+s+" scale("+this.scale+")":(b=e.round(b),h=e.round(h),this.scroller.style.left=b+"px",this.scroller.style.top=h+"px");this.x=b;this.y=
h},_start:function(b){var h=g?b.touches[0]:b,p,e;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,b);this.options.useTransition&&this._transitionTime(0);this.zoomed=this.animating=this.moved=!1;this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;if(this.options.momentum&&(this.options.useTransform?(p=getComputedStyle(this.scroller,null)[f+"Transform"].replace(/[^0-9-.,]/g,"").split(","),e=1*p[4],p=1*p[5]):(e=1*getComputedStyle(this.scroller,
null).left.replace(/[^0-9-]/g,""),p=1*getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")),e!=this.x||p!=this.y))this.options.useTransition?this._unbind("webkitTransitionEnd"):n(this.aniTime),this.steps=[],this._pos(e,p);this.absStartX=this.x;this.absStartY=this.y;this.startX=this.x;this.startY=this.y;this.pointX=h.pageX;this.pointY=h.pageY;this.startTime=b.timeStamp||Date.now();this.options.onScrollStart&&this.options.onScrollStart.call(this,b);this._bind(t);this._bind(r);this._bind(v)}},
_move:function(b){var h=g?b.touches[0]:b,p=h.pageX-this.pointX,d=h.pageY-this.pointY,f=this.x+p,a=this.y+d,c=b.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,b);this.pointX=h.pageX;this.pointY=h.pageY;if(0<f||f<this.maxScrollX)f=this.options.bounce?this.x+p/2:0<=f||0<=this.maxScrollX?0:this.maxScrollX;if(0<a||a<this.maxScrollY)a=this.options.bounce?this.y+d/2:0<=a||0<=this.maxScrollY?0:this.maxScrollY;if(6>this.absDistX&&6>this.absDistY)this.distX+=
p,this.distY+=d,this.absDistX=e.abs(this.distX),this.absDistY=e.abs(this.distY);else{if(this.options.lockDirection)if(this.absDistX>this.absDistY+5)a=this.y,d=0;else if(this.absDistY>this.absDistX+5)f=this.x,p=0;this.moved=!0;this._pos(f,a);this.dirX=0<p?-1:0>p?1:0;this.dirY=0<d?-1:0>d?1:0;if(300<c-this.startTime)this.startTime=c,this.startX=this.x,this.startY=this.y;this.options.onScrollMove&&this.options.onScrollMove.call(this,b)}},_end:function(b){if(!(g&&0!=b.touches.length)){var h=g?b.changedTouches[0]:
b,p,d,f={dist:0,time:0},a={dist:0,time:0},c=(b.timeStamp||Date.now())-this.startTime;p=this.x;d=this.y;this._unbind(t);this._unbind(r);this._unbind(v);this.options.onBeforeScrollEnd&&this.options.onBeforeScrollEnd.call(this,b);if(this.moved){if(300>c&&this.options.momentum){f=p?this._momentum(p-this.startX,c,-this.x,this.scrollerW-this.wrapperW+this.x,this.options.bounce?this.wrapperW:0):f;a=d?this._momentum(d-this.startY,c,-this.y,0>this.maxScrollY?this.scrollerH-this.wrapperH+this.y:0,this.options.bounce?
this.wrapperH:0):a;p=this.x+f.dist;d=this.y+a.dist;if(0<this.x&&0<p||this.x<this.maxScrollX&&p<this.maxScrollX)f={dist:0,time:0};if(0<this.y&&0<d||this.y<this.maxScrollY&&d<this.maxScrollY)a={dist:0,time:0}}f.dist||a.dist?(h=e.max(e.max(f.time,a.time),10),this.scrollTo(p,d,h)):this._resetPos(200)}else{if(g){for(p=h.target;1!=p.nodeType;)p=p.parentNode;if("SELECT"!=p.tagName&&"INPUT"!=p.tagName&&"TEXTAREA"!=p.tagName)d=document.createEvent("MouseEvents"),d.initMouseEvent("click",!0,!0,b.view,1,h.screenX,
h.screenY,h.clientX,h.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null),d._fake=!0,p.dispatchEvent(d)}this._resetPos(200)}this.options.onTouchEnd&&this.options.onTouchEnd.call(this,b)}},_resetPos:function(b){var h=0<=this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,d=0<=this.y||0<this.maxScrollY?0:this.y<this.maxScrollY?this.maxScrollY:this.y;if(h==this.x&&d==this.y){if(this.moved)this.options.onScrollEnd&&this.options.onScrollEnd.call(this),this.moved=!1}else this.scrollTo(h,d,b||0)},
_mouseout:function(b){var h=b.relatedTarget;if(h)for(;h=h.parentNode;)if(h==this.wrapper)return;this._end(b)},_transitionEnd:function(b){b.target==this.scroller&&(this._unbind("webkitTransitionEnd"),this._startAni())},_startAni:function(){var b=this,h=b.x,d=b.y,f=Date.now(),a,c,g;if(!b.animating)if(b.steps.length){a=b.steps.shift();if(a.x==h&&a.y==d)a.time=0;b.animating=!0;b.moved=!0;b.options.useTransition?(b._transitionTime(a.time),b._pos(a.x,a.y),b.animating=!1,a.time?b._bind("webkitTransitionEnd"):
b._resetPos(0)):(g=function(){var i=Date.now();if(i>=f+a.time)b._pos(a.x,a.y),b.animating=!1,b.options.onAnimationEnd&&b.options.onAnimationEnd.call(b),b._startAni();else if(i=(i-f)/a.time-1,c=e.sqrt(1-i*i),i=(a.x-h)*c+h,b._pos(i,(a.y-d)*c+d),b.animating)b.aniTime=q(g)},g())}else b._resetPos(400)},_transitionTime:function(b){this.scroller.style[f+"TransitionDuration"]=b+"ms"},_momentum:function(b,h,d,a,f){var h=e.abs(b)/h,c=h*h/0.0012,g=0,g=0;0<b&&c>d?(d+=f/(6/(6.0E-4*(c/h))),h=h*d/c,c=d):0>b&&c>
a&&(a+=f/(6/(6.0E-4*(c/h))),h=h*a/c,c=a);return{dist:c*(0>b?-1:1),time:e.round(h/6.0E-4)}},_offset:function(b){for(var d=-b.offsetLeft,a=-b.offsetTop;b=b.offsetParent;)d-=b.offsetLeft,a-=b.offsetTop;return{left:d,top:a}},_bind:function(b,d,a){(d||this.scroller).addEventListener(b,this,!!a)},_unbind:function(b,d,a){(d||this.scroller).removeEventListener(b,this,!!a)},destroy:function(){this.scroller.style[f+"Transform"]="";this._unbind(d,window);this._unbind(i);this._unbind(t);this._unbind(r);this._unbind(v);
this._unbind("mouseout",this.wrapper);this.options.useTransition&&this._unbind("webkitTransitionEnd");this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var b;this.wrapperW=this.wrapper.clientWidth;this.wrapperH=this.wrapper.clientHeight;this.scrollerW=this.scroller.offsetWidth;this.scrollerH=this.scroller.offsetHeight;this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH;this.dirY=this.dirX=0;this.hScroll=this.options.hScroll&&0>this.maxScrollX;
this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);b=this._offset(this.wrapper);this.wrapperOffsetLeft=-b.left;this.wrapperOffsetTop=-b.top;this.scroller.style[f+"TransitionDuration"]="0";this._resetPos(200)},scrollTo:function(b,d,a,f){var c=b;this.stop();c.length||(c=[{x:b,y:d,time:a,relative:f}]);for(b=0,d=c.length;b<d;b++){if(c[b].relative)c[b].x=this.x-c[b].x,c[b].y=this.y-c[b].y;this.steps.push({x:c[b].x,y:c[b].y,time:c[b].time||0})}this._startAni()},
scrollToElement:function(b,d){var a;if(b=b.nodeType?b:this.scroller.querySelector(b))a=this._offset(b),a.left+=this.wrapperOffsetLeft,a.top+=this.wrapperOffsetTop,a.left=0<a.left?0:a.left<this.maxScrollX?this.maxScrollX:a.left,a.top=0<a.top?0:a.top<this.maxScrollY?this.maxScrollY:a.top,d=void 0===d?e.max(2*e.abs(a.left),2*e.abs(a.top)):d,this.scrollTo(a.left,a.top,d)},disable:function(){this.stop();this._resetPos(0);this.enabled=!1;this._unbind(t);this._unbind(r);this._unbind(v)},enable:function(){this.enabled=
!0},stop:function(){n(this.aniTime);this.steps=[];this.animating=this.moved=!1}};"undefined"!==typeof exports?exports.iScroll=j:window.iScroll=j})();var requirejs,require,define;
(function(){function e(b){return"[object Function]"===t.call(b)}function f(b){return"[object Array]"===t.call(b)}function j(b,a,d){for(var c in a)if(!(c in F)&&(!(c in b)||d))b[c]=a[c];return o}function g(b,a,d){b=Error(a+"\nhttp://requirejs.org/docs/errors.html#"+b);if(d)b.originalError=d;return b}function m(b,a,c){var f,h,e;for(f=0;e=a[f];f++){e="string"===typeof e?{name:e}:e;h=e.location;if(c&&(!h||0!==h.indexOf("/")&&-1===h.indexOf(":")))h=c+"/"+(h||e.name);b[e.name]={name:e.name,location:h||
e.name,main:(e.main||"main").replace(d,"").replace(i,"")}}}function a(b,a){b.holdReady?b.holdReady(a):a?b.readyWait+=1:b.ready(!0)}function k(d){function c(b,a){var d,f;if(b&&"."===b.charAt(0)&&a){w.pkgs[a]?a=[a]:(a=a.split("/"),a=a.slice(0,a.length-1));d=b=a.concat(b.split("/"));var h;for(f=0;h=d[f];f++)if("."===h)d.splice(f,1),f-=1;else if(".."===h)if(1===f&&(".."===d[2]||".."===d[0]))break;else 0<f&&(d.splice(f-1,2),f-=2);f=w.pkgs[d=b[0]];b=b.join("/");f&&b===d+"/"+f.main&&(b=d)}return b}function f(b,
a){var d=b?b.indexOf("!"):-1,h=null,e=a?a.name:null,i=b,g,k;-1!==d&&(h=b.substring(0,d),b=b.substring(d+1,b.length));h&&(h=c(h,e));b&&(h?g=(d=u[h])&&d.normalize?d.normalize(b,function(b){return c(b,e)}):c(b,e):(g=c(b,e),k=H[g],k||(k=l.nameToUrl(g,null,a),H[g]=k)));return{prefix:h,name:g,parentMap:a,url:k,originalName:i,fullName:h?h+"!"+(g||""):g}}function h(){var b=!0,a=w.priorityWait,d,f;if(a){for(f=0;d=a[f];f++)if(!C[d]){b=!1;break}b&&delete w.priorityWait}return b}function i(b,a,d){return function(){var f=
v.call(arguments,0),c;if(d&&e(c=f[f.length-1]))c.__requireJsBuild=!0;f.push(a);return b.apply(null,f)}}function k(b,a){var d=i(l.require,b,a);j(d,{nameToUrl:i(l.nameToUrl,b),toUrl:i(l.toUrl,b),defined:i(l.requireDefined,b),specified:i(l.requireSpecified,b),isBrowser:o.isBrowser});return d}function n(b){var a,d,c;c=b.callback;var h=b.map,i=h.fullName,k=b.deps,s=b.listeners;if(c&&e(c)){if(w.catchError.define)try{d=o.execCb(i,b.callback,k,u[i])}catch(j){a=j}else d=o.execCb(i,b.callback,k,u[i]);if(i)b.cjsModule&&
void 0!==b.cjsModule.exports?d=u[i]=b.cjsModule.exports:void 0===d&&b.usingExports?d=u[i]:(u[i]=d,L[i]&&(S[i]=!0))}else i&&(d=u[i]=c,L[i]&&(S[i]=!0));if(J[b.id])delete J[b.id],b.isDone=!0,l.waitCount-=1,0===l.waitCount&&(K=[]);delete T[i];if(o.onResourceLoad&&!b.placeholder)o.onResourceLoad(l,h,b.depArray);if(a)return d=(i?f(i).url:"")||a.fileName||a.sourceURL,c=a.moduleTree,a=g("defineerror",'Error evaluating module "'+i+'" at location "'+d+'":\n'+a+"\nfileName:"+d+"\nlineNumber: "+(a.lineNumber||
a.line),a),a.moduleName=i,a.moduleTree=c,o.onError(a);for(a=0;c=s[a];a++)c(d)}function p(b,a){return function(d){b.depDone[a]||(b.depDone[a]=!0,b.deps[a]=d,b.depCount-=1,b.depCount||n(b))}}function q(b,a){var d=a.map,f=d.fullName,c=d.name,h=O[b]||(O[b]=u[b]),i;if(!a.loading)a.loading=!0,i=function(b){a.callback=function(){return b};n(a);C[a.id]=!0;x()},i.fromText=function(b,a){var d=P;C[b]=!1;l.scriptCount+=1;l.fake[b]=!0;d&&(P=!1);o.exec(a);d&&(P=!0);l.completeLoad(b)},f in u?i(u[f]):h.load(c,k(d.parentMap,
!0),i,w)}function t(b){J[b.id]||(J[b.id]=b,K.push(b),l.waitCount+=1)}function r(b){this.listeners.push(b)}function y(b,a){var d=b.fullName,c=b.prefix,h=c?O[c]||(O[c]=u[c]):null,i,e;d&&(i=T[d]);if(!i&&(e=!0,i={id:(c&&!h?X++ +"__p@:":"")+(d||"__r@"+X++),map:b,depCount:0,depDone:[],depCallbacks:[],deps:[],listeners:[],add:r},E[i.id]=!0,d&&(!c||O[c])))T[d]=i;c&&!h?(d=y(f(c),!0),d.add(function(){var a=f(b.originalName,b.parentMap),a=y(a,!0);i.placeholder=!0;a.add(function(b){i.callback=function(){return b};
n(i)})})):e&&a&&(C[i.id]=!1,l.paused.push(i),t(i));return i}function G(b,a,d,c){var b=f(b,c),i=b.name,h=b.fullName,e=y(b),g=e.id,s=e.deps,j;if(h){if(h in u||!0===C[g]||"jquery"===h&&w.jQuery&&w.jQuery!==d().fn.jquery)return;E[g]=!0;C[g]=!0;"jquery"===h&&d&&U(d())}e.depArray=a;e.callback=d;for(d=0;d<a.length;d++)if(g=a[d])g=f(g,i?b:c),j=g.fullName,a[d]=j,"require"===j?s[d]=k(b):"exports"===j?(s[d]=u[h]={},e.usingExports=!0):"module"===j?e.cjsModule=s[d]={id:i,uri:i?l.nameToUrl(i,null,c):void 0,exports:u[h]}:
j in u&&!(j in J)&&(!(h in L)||h in L&&S[j])?s[d]=u[j]:(h in L&&(L[j]=!0,delete u[j],V[g.url]=!1),e.depCount+=1,e.depCallbacks[d]=p(e,d),y(g,!0).add(e.depCallbacks[d]));e.depCount?t(e):n(e)}function z(b){G.apply(null,b)}function N(b,a){if(!b.isDone){var d=b.map.fullName,c=b.depArray,h,i,e,g;if(d){if(a[d])return u[d];a[d]=!0}if(c)for(h=0;h<c.length;h++)if(i=c[h])if((e=f(i).prefix)&&(g=J[e])&&N(g,a),(e=J[i])&&!e.isDone&&C[i])i=N(e,a),b.depCallbacks[h](i);return d?u[d]:void 0}}function D(){var a=1E3*
w.waitSeconds,d=a&&l.startTime+a<(new Date).getTime(),a="",c=!1,i=!1,f;if(!(0<l.pausedCount)){if(w.priorityWait)if(h())x();else return;for(f in C)if(!(f in F)&&(c=!0,!C[f]))if(d)a+=f+" ";else{i=!0;break}if(c||l.waitCount){if(d&&a)return f=g("timeout","Load timeout for modules: "+a),f.requireType="timeout",f.requireModules=a,o.onError(f);if(i||l.scriptCount){if((s||b)&&!W)W=setTimeout(function(){W=0;D()},50)}else{if(l.waitCount){for(M=0;a=K[M];M++)N(a,{});l.paused.length&&x();5>R&&(R+=1,D())}R=0;o.checkReadyState()}}}}
var l,x,w={waitSeconds:7,baseUrl:"./",paths:{},pkgs:{},catchError:{}},A=[],E={require:!0,exports:!0,module:!0},H={},u={},C={},J={},K=[],V={},X=0,T={},O={},L={},S={},Q=0;U=function(b){if(!l.jQuery&&(b=b||("undefined"!==typeof jQuery?jQuery:null))&&!(w.jQuery&&b.fn.jquery!==w.jQuery)&&("holdReady"in b||"readyWait"in b))if(l.jQuery=b,z(["jquery",[],function(){return jQuery}]),l.scriptCount)a(b,!0),l.jQueryIncremented=!0};x=function(){var b,a,d,c,f,i;Q+=1;if(0>=l.scriptCount)l.scriptCount=0;for(;A.length;){b=
A.shift();if(null===b[0])return o.onError(g("mismatch","Mismatched anonymous define() module: "+b[b.length-1]));z(b)}if(!w.priorityWait||h())for(;l.paused.length;){f=l.paused;l.pausedCount+=f.length;l.paused=[];for(c=0;b=f[c];c++)a=b.map,d=a.url,i=a.fullName,a.prefix?q(a.prefix,b):!V[d]&&!C[i]&&(o.load(l,i,d),V[d]=!0);l.startTime=(new Date).getTime();l.pausedCount-=f.length}1===Q&&D();Q-=1};l={contextName:d,config:w,defQueue:A,waiting:J,waitCount:0,specified:E,loaded:C,urlMap:H,urlFetched:V,scriptCount:0,
defined:u,paused:[],pausedCount:0,plugins:O,needFullExec:L,fake:{},fullExec:S,managerCallbacks:T,makeModuleMap:f,normalize:c,configure:function(b){var a,d,c;b.baseUrl&&"/"!==b.baseUrl.charAt(b.baseUrl.length-1)&&(b.baseUrl+="/");a=w.paths;c=w.pkgs;j(w,b,!0);if(b.paths){for(d in b.paths)d in F||(a[d]=b.paths[d]);w.paths=a}if((a=b.packagePaths)||b.packages){if(a)for(d in a)d in F||m(c,a[d],d);b.packages&&m(c,b.packages);w.pkgs=c}if(b.priority)d=l.requireWait,l.requireWait=!1,l.takeGlobalQueue(),x(),
l.require(b.priority),x(),l.requireWait=d,w.priorityWait=b.priority;if(b.deps||b.callback)l.require(b.deps||[],b.callback)},requireDefined:function(b,a){return f(b,a).fullName in u},requireSpecified:function(b,a){return f(b,a).fullName in E},require:function(b,a,c){if("string"===typeof b){if(e(a))return o.onError(g("requireargs","Invalid require call"));if(o.get)return o.get(l,b,a);a=f(b,a);b=a.fullName;return!(b in u)?o.onError(g("notloaded","Module name '"+a.fullName+"' has not been loaded yet for context: "+
d)):u[b]}(b&&b.length||a)&&G(null,b,a,c);if(!l.requireWait)for(;!l.scriptCount&&l.paused.length;)l.takeGlobalQueue(),x();return l.require},takeGlobalQueue:function(){I.length&&(B.apply(l.defQueue,[l.defQueue.length-1,0].concat(I)),I=[])},completeLoad:function(b){var a;for(l.takeGlobalQueue();A.length;)if(a=A.shift(),null===a[0]){a[0]=b;break}else if(a[0]===b)break;else z(a),a=null;a?z(a):z([b,[],"jquery"===b&&"undefined"!==typeof jQuery?function(){return jQuery}:null]);U();o.isAsync&&(l.scriptCount-=
1);x();o.isAsync||(l.scriptCount-=1)},toUrl:function(b,a){var d=b.lastIndexOf("."),c=null;-1!==d&&(c=b.substring(d,b.length),b=b.substring(0,d));return l.nameToUrl(b,c,a)},nameToUrl:function(b,a,d){var f,i,h,e,g=l.config,b=c(b,d&&d.fullName);if(o.jsExtRegExp.test(b))a=b+(a?a:"");else{f=g.paths;i=g.pkgs;d=b.split("/");for(e=d.length;0<e;e--)if(h=d.slice(0,e).join("/"),f[h]){d.splice(0,e,f[h]);break}else if(h=i[h]){b=b===h.name?h.location+"/"+h.main:h.location;d.splice(0,e,b);break}a=d.join("/")+(a||
".js");a=("/"===a.charAt(0)||a.match(/^\w+:/)?"":g.baseUrl)+a}return g.urlArgs?a+((-1===a.indexOf("?")?"?":"&")+g.urlArgs):a}};l.jQueryCheck=U;l.resume=x;return l}function c(){var b,a,d;if(G&&"interactive"===G.readyState)return G;b=document.getElementsByTagName("script");for(a=b.length-1;-1<a&&(d=b[a]);a--)if("interactive"===d.readyState)return G=d;return null}var q=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,n=/require\(\s*["']([^'"\s]+)["']\s*\)/g,d=/^\.\//,i=/\.js$/,t=Object.prototype.toString,
r=Array.prototype,v=r.slice,B=r.splice,s=!!("undefined"!==typeof window&&navigator&&document),b=!s&&"undefined"!==typeof importScripts,h=s&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,p="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),F={},y={},I=[],G=null,R=0,P=!1,o,r={},N,z,D,K,x,E,H,M,A,U,W;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(e(requirejs))return;r=requirejs;requirejs=void 0}"undefined"!==typeof require&&!e(require)&&(r=
require,require=void 0);o=requirejs=function(b,a,d){var c="_",h;!f(b)&&"string"!==typeof b&&(h=b,f(a)?(b=a,a=d):b=[]);if(h&&h.context)c=h.context;d=y[c]||(y[c]=k(c));h&&d.configure(h);return d.require(b,a)};o.config=function(b){return o(b)};require||(require=o);o.toUrl=function(b){return y._.toUrl(b)};o.version="1.0.1";o.jsExtRegExp=/^\/|:|\?|\.js$/;z=o.s={contexts:y,skipAsync:{}};if(o.isAsync=o.isBrowser=s)if(D=z.head=document.getElementsByTagName("head")[0],K=document.getElementsByTagName("base")[0])D=
z.head=K.parentNode;o.onError=function(b){throw b;};o.load=function(b,d,c){o.resourcesReady(!1);b.scriptCount+=1;o.attach(c,b,d);if(b.jQuery&&!b.jQueryIncremented)a(b.jQuery,!0),b.jQueryIncremented=!0};define=function(b,a,d){var h,i;"string"!==typeof b&&(d=a,a=b,b=null);f(a)||(d=a,a=[]);!a.length&&e(d)&&d.length&&(d.toString().replace(q,"").replace(n,function(b,d){a.push(d)}),a=(1===d.length?["require"]:["require","exports","module"]).concat(a));if(P&&(h=N||c()))b||(b=h.getAttribute("data-requiremodule")),
i=y[h.getAttribute("data-requirecontext")];(i?i.defQueue:I).push([b,a,d])};define.amd={multiversion:!0,plugins:!0,jQuery:!0};o.exec=function(b){return eval(b)};o.execCb=function(b,a,d,c){return a.apply(c,d)};o.addScriptToDom=function(b){N=b;K?D.insertBefore(b,K):D.appendChild(b);N=null};o.onScriptLoad=function(b){var a=b.currentTarget||b.srcElement,d;if("load"===b.type||a&&h.test(a.readyState))G=null,b=a.getAttribute("data-requirecontext"),d=a.getAttribute("data-requiremodule"),y[b].completeLoad(d),
a.detachEvent&&!p?a.detachEvent("onreadystatechange",o.onScriptLoad):a.removeEventListener("load",o.onScriptLoad,!1)};o.attach=function(a,d,c,h,f,i){var e;if(s)return h=h||o.onScriptLoad,e=d&&d.config&&d.config.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script"),e.type=f||"text/javascript",e.charset="utf-8",e.async=!z.skipAsync[a],d&&e.setAttribute("data-requirecontext",d.contextName),e.setAttribute("data-requiremodule",c),e.attachEvent&&!p?
(P=!0,i?e.onreadystatechange=function(){if("loaded"===e.readyState)e.onreadystatechange=null,e.attachEvent("onreadystatechange",h),i(e)}:e.attachEvent("onreadystatechange",h)):e.addEventListener("load",h,!1),e.src=a,i||o.addScriptToDom(e),e;b&&(importScripts(a),d.completeLoad(c));return null};if(s){x=document.getElementsByTagName("script");for(M=x.length-1;-1<M&&(E=x[M]);M--){if(!D)D=E.parentNode;if(H=E.getAttribute("data-main")){if(!r.baseUrl)x=H.split("/"),E=x.pop(),x=x.length?x.join("/")+"/":"./",
r.baseUrl=x,H=E.replace(i,"");r.deps=r.deps?r.deps.concat(H):[H];break}}}o.checkReadyState=function(){var b=z.contexts,a;for(a in b)if(!(a in F)&&b[a].waitCount)return;o.resourcesReady(!0)};o.resourcesReady=function(b){var d,c;o.resourcesDone=b;if(o.resourcesDone)for(c in b=z.contexts,b)if(!(c in F)&&(d=b[c],d.jQueryIncremented))a(d.jQuery,!1),d.jQueryIncremented=!1};o.pageLoaded=function(){if("complete"!==document.readyState)document.readyState="complete"};if(s&&document.addEventListener&&!document.readyState)document.readyState=
"loading",window.addEventListener("load",o.pageLoaded,!1);o(r);if(o.isAsync&&"undefined"!==typeof setTimeout)A=z.contexts[r.context||"_"],A.requireWait=!0,setTimeout(function(){A.requireWait=!1;A.takeGlobalQueue();A.jQueryCheck();A.scriptCount||A.resume();o.checkReadyState()},0)}})();define("requireLib",function(){});
(function(){var e,f,j,g,m,a,k,c,q,n,d,i,t=Array.prototype.slice,r=Object.prototype.hasOwnProperty,v=function(a,d){function b(){this.constructor=a}for(var c in d)r.call(d,c)&&(a[c]=d[c]);b.prototype=d.prototype;a.prototype=new b;a.__super__=d.prototype;return a};e="function"===typeof("undefined"!==typeof console&&null!==console?console.error:void 0)&&function(a){return console.error(a)}||function(){};m=this;j=m.document||{createElement:function(){}};q="object"===typeof Node?function(a){return a instanceof
Node}:function(a){return"object"===typeof a&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName};c=Array.isArray?Array.isArray:function(){return function(a){return a.push===push&&null!=a.length}}();a=Function.prototype.bind?function(a,d){return a.bind(d)}:function(a,d){return function(){return a.apply(d,arguments)}};k=function(){return j.createElement("div")};i=k();d=function(a,d){for(var b,h;0<d.length;)if(null!=(b=d.shift()))q(b)?a.appendChild(b):"string"===(h=typeof b)||"number"===h?a.appendChild(j.createTextNode(b)):
c(b)?Array.prototype.unshift.apply(d,b):e("renderNodes: unsupported child type = "+b);return a};m.cell=f=function(){function f(i){var b,h,e,g,j,k,n;this.options=null!=i?i:{};if(null!=this.options.model)this.model=this.options.model;"function"===typeof this.init&&this.init(this.options);this.$el=jQuery(this.el=this._tag());if(i=this.options.id)this.el.id=i;n=[this.cell.prototype.name,this["class"],this.options["class"]];for(i=0,k=n.length;i<k;i++)if(j=n[i])this.el.className+=i&&" "+j||j;d(this.el,
c(e="function"===typeof this.render?this.render(this.$R):void 0)&&e||[]);i=this.on;for(b in i)if(e=i[b],"function"===typeof e&&(g=/^([A-z]+)(\s(.*))?$/.exec(b))&&(h=g[1]))this.$el.on(h,g[3],a(e,this));"function"===typeof this.afterRender&&this.afterRender()}f.prototype.$=function(a){return jQuery(a,this.el)};f.prototype.$R=function(){var a,b,c,f,g,k,n,m;a=arguments[0];b=arguments[1];c=3<=arguments.length?t.call(arguments,2):[];if(a){if((null!=b?b.constructor:void 0)!==Object)c.unshift(b),b=void 0;
return(n=function(){if("string"===typeof a){if(k=/^(\w+)?(#([\w\-]+))*(\.[\w\.\-]+)?$/.exec(a)){f=j.createElement(k[1]||"div");if(m=k[3])f.id=m;if(b)for(g in"class"in b&&(f.className+=b["class"],delete b["class"]),b)m=b[g],f.setAttribute(g,m);if(m=k[4])f.className+=m.replace(/\./g," ");return f}return/^<[A-z]/.test(a)?(i.innerHTML=a,i.children[0]):e("renderParent: unsupported parent string = '"+a+"'")}return a.prototype.cell===a?(new a(b)).el:q(a)?a:e("renderParent: unsupported parent type = "+a)}())&&
d(n,c)}};return f}();f.extend=function(a){var d,b,c,e,g;null==a&&(a={});if("object"!==typeof a)throw"cell.extend(): expects an object {render,init,name}";if(a.init&&"function"!==typeof a.init||a.render&&"function"!==typeof a.render)throw"cell.extend(): expects {render,init} to be functions";d=function(){function b(){b.__super__.constructor.apply(this,arguments)}v(b,f);return b}();for(b in a)g=a[b],d.prototype[b]=g;d.prototype.cell=d;d.prototype._tag="string"===(e=typeof a.tag)?function(){i.innerHTML=
a.tag;return i.children[0]||k()}:"function"===e?function(){i.innerHTML=this.tag();return i.children[0]||k()}:k;if("string"===typeof(b=a.css))c=j.createElement("style"),c.innerHTML=b;else if("string"===typeof(b=a.css_href))c=j.createElement("link"),c.href=b,c.rel="stylesheet";if(c)c.type="text/css",$("head")[0].appendChild(c);return d};"function"===typeof define&&"function"===typeof require&&(n=/(.*\/)?(.*)$/,define("cell",[],g={pluginBuilder:"cell-builder-plugin",load:function(a,d,b){d([a],function(c){var i;
if("object"!==typeof c)e("Couldn't load "+a+" cell. cell definitions should be objects, but instead was "+typeof c);else{c.name=n.exec(a)[2];if(null==(null!=(i=g.__preinstalledCells__)?i[a]:void 0)&&null==c.css_href)c.css_href=d.toUrl(""+a+".css");"string"===typeof c["extends"]?d(["cell!"+c["extends"]],function(a){a.prototype.name&&(c["class"]=a.prototype.name+(" "+c["class"])||"");b(a.extend(c))}):b(f.extend(c))}})}}),jQuery(j).ready(function(){jQuery("[data-cell]").each(function(){var a,d,b,c,i=
this;if(b=this.getAttribute("data-cell")){c={};a=/(^\?cachebust)|(&cachebust)/.test(m.location.search);if((null!==(d=this.getAttribute("data-cell-cachebust"))||a)&&"false"!==d)c.urlArgs="bust="+(new Date).getTime();if(a=this.getAttribute("data-cell-baseurl"))c.baseUrl=a;require(c,["cell!"+b],function(b){jQuery(i).append((new b).el)})}})}))}).call(this);
define("AppConfig",["cell!pages/schedule/Schedule"],function(){return{contexts:{Schedule:{defaultPagePath:"pages/schedule/Schedule"},Watch:{defaultPagePath:"pages/watch/Watch"},Search:{defaultPagePath:"pages/watch/Watch"}},defaultContext:"Schedule"}});var __slice=Array.prototype.slice;
define("data/JSONP",[],function(){var e,f,j,g;f=function(f){return f};g=0;j=function(f){var a,e;a="__jsonp"+ ++g;window[a]=function(c){f.success(c);window[a]=void 0;return $("#"+a).remove()};if(null==f.callback)f.callback="callback";e=document.createElement("script");e.id=a;e.setAttribute("type","text/javascript");e.setAttribute("src",""+f.url+(-1===f.url.indexOf("?")&&"?"||"&")+f.callback+"="+a);return $("head").append(e)};e=-1<window.location.search.indexOf("mock-service=true")?function(f,a){var e,
c;e=f.mock;c=f.real;return setTimeout(function(){return require([e],function(f){return a("function"===typeof f?f(c):f)})},0)}:function(f,a){return j({callback:"jsonp",url:f.real,success:a||function(){}})};return{JSONPService:function(){return function(g,a){var j,c,q,n,d,i,t=this;j=a.baseURL;d=a.process;c=a.methods;null==d&&(d=f);i=function(a,c){var i,n,b;n=d;i=f;if("object"===(b=typeof c)&&"function"!==b){if(null!=c.process)n=c.process;c=c.path;if(null!=c.getCache)i=c.getCache}"string"===typeof c&&
function(){var b;b=c;return c=function(){return b}}();return t[a]=function(){var b,d,t,q;b=2<=arguments.length?__slice.call(arguments,0,q=arguments.length-1):(q=0,[]);t=arguments[q++];null==t&&(t=f);void 0!==(d=i())?t(d):e({mock:"data/mock/"+g+"/"+a,real:j+c.apply(null,b)},function(b){b=n(b);t(b)})}};for(q in c)n=c[q],i(q,n)}}()}});
define("data/UserService",["data/JSONP"],function(e){return new e.JSONPService("users",{baseURL:"api/users/",methods:{getWatchedShows:function(){return"pwong/watched-shows"},getShows:function(f){return"pwong/schedule/"+(f.getYear()+1900)+"-"+f.getMonth()+"-"+f.getDate()}}})});define("data/ActorService",["data/JSONP"],function(e){return new e.JSONPService("actors",{baseURL:"api/actors/",methods:{getDetails:function(f){return""+f}}})});
define("data/ShowService",["data/JSONP"],function(e){return new e.JSONPService("shows",{baseURL:"api/shows/",methods:{getDetails:function(f){return""+f}}})});define("Services",["data/UserService","data/ActorService","data/ShowService"],function(e,f,j){return{user:e,show:j,actor:f}});
define("shared/DateHelper",[],function(){var e,f,j;j=new Date;f=["Today","Yesterday"].concat(function(){var f;f=[];for(e=2;7>e;e++)f.push(""+e+" days ago");return f}(),"a week ago");return{getDisplayable:function(e){return j.getYear()===e.getYear()&&j.getMonth()===e.getMonth()?f[j.getDate()-e.getDate()]:e.toLocaleDateString()}}});
define("pages/schedule/Schedule",["require","Services","shared/DateHelper","cell!shared/ListView"],function(e,f,j,g){return{init:function(){var f=this;this.model.set({title:j.getDisplayable(new Date)});return this.model.bind({activate:function(){return f.$("#ShowList").trigger("resetActive")}})},render:function(j){var a=this;return f.user.getShows(new Date,function(f){var c;a.$el.append(j(g,{id:"ShowList",list:function(){var a,e,d;d=[];for(a=0,e=f.length;a<e;a++)c=f[a],d.push({link:"pages/showdetails/ShowDetails?id="+
c.id+"&title="+c.title,text:c.title});return d}()}));a.model.trigger("refreshScroller");return e(["pages/showdetails/ShowDetails"],function(){})})}}});
define("shared/ListView",{tag:"<ul>",render:function(e){var f,j,g,m,a,k,c,q;if(g=this.options.list){q=[];for(a=0,k=g.length;a<k;a++)if(c=g[a],m=c.text,j=c.link,f=c.dividerText,m||f)m?q.push(e("<li data-navto='"+j+"'>",e("div"),m)):q.push(e("li.divider",f));return q}},on:{resetActive:function(){return this.$("li.active").removeClass("active").addClass("deactive")},"webkitAnimationEnd li > div":function(){return this.$("li.deactive").removeClass("deactive")},"click li":function(e){e=e.target;this.$("li.active").removeClass("active");
return $(e).closest("li").addClass("active")}}});define("HashDelegate",{set:function(e){return window.location.hash=e},get:function(){return window.location.hash},onChange:function(e){return $(window).on("hashchange",e)}});
define("framework/Model",[],function(){var e,f;e=/^change:(.*)/;f=function(f,e){var m,a,k;for(a=0,k=f.length;a<k;a++)if(m=f[a],m===e)return;return f.unshift(e)};return function(){function j(a){var f,c;this._ls={};for(f in a)c=a[f],this[f]=c}var g,m;j.pathObj=m=function(a,f){var c,e;if(a){e=f.length;for(c=0;c<e&&null!=(a=a[f[c++]]););return a}};j.parsePropChange=g=function(a){var f,c;return null!=(f=e.exec(a))?null!=(c=f[1])?c.split("."):void 0:void 0};j.prototype.set=function(a,f){var c,e,g;for(c in a)if(g=
a[c],this[c]!==g){e=this[c];try{this.trigger({cur:this[c]=g,prev:e,property:c,type:"change:"+c,data:f})}catch(d){}}};j.prototype.trigger=function(a,f){var c,e,g,d,i;c="string"===typeof a?{type:a,data:f}:a;c.model=this;if(g=this._ls[c.type])for(d=0,i=g.length;d<i;d++){e=g[d];try{e(c)}catch(j){}}};j.prototype.bindAndCall=function(a){var e,c,q,n;c=this;n=function(a){var e,n,k,v,B,s,b,h,p,F,y;if(s=g(q)){n=s.length-1;p=s[n];B=s.slice(0,n);b=function(b,a){var d,c,e;return f(null!=(e=(d=a._ls)[c="change:"+
s[b]])?e:d[c]=[],h[b])};k=c;h=[];F=function(c){h[c]=function(f){for(var e=c,i=f.cur,h=f.prev,g=f.model;e++<n;i=(g=i)&&i[s[e]],h=h&&h[s[e]])i instanceof j&&b(e,i);e={cur:i,prev:h,property:p,type:"change:"+p,model:g,data:f.data};if(c!==n)e.parentEvent=f;return a(e)};if(k instanceof j)return b(c,k),k=k[v]};for(e=0,y=s.length;e<y;e++)v=s[e],F(e);try{return a({cur:k,property:p,type:q,model:m(c,B)})}catch(I){return console.error((null!=I?I.stack:void 0)||I)}}else{f(null!=(B=(e=c._ls)[q])?B:e[q]=[],a);try{return a({type:q,
model:c})}catch(G){}}};for(q in a)e=a[q],n(e)};j.prototype.bind=function(a){var e,c,m,n,d,i,t,r,v,B;for(n in a){c=a[n];if(e=g(n)){v=e.slice(0,-1);for(t=0,r=v.length;t<r;t++)if(m=v[t],(d=this[m])instanceof j)e={},e["change:"+m]=function(){},d.bind(e)}f(null!=(B=(i=this._ls)[n])?B:i[n]=[],c)}};j.prototype.unbind=function(a){var f,c,e,g,d,i;for(d in a)if(f=a[d],g=this._ls[d])for(c=0,i=g.length;c<i;c++)e=g[c],e===f&&delete g[c]};return j}()});
define("framework/Nav",["AppConfig","HashDelegate","./Model"],function(e,f,j){var g,m,a,k,c,q,n;k=/^\#([^!^?]+)(!([^?]+))?(\?(.+))?/;n=void 0;g=new j({toHash:q=function(a){var c,f,g,j;c=a.context;f=a.page;a=a.data;c=e.contexts[c]&&c||e.defaultContext;f="#"+c+"!"+(f||e.contexts[c].defaultPagePath);if(a)for(g in c="?",a)j=a[g],f+=""+c+g+"="+encodeURIComponent(j),c="&";return f},parseHash:c=function(a){var c,f,g,j;j=k.exec(a);var n=c=(f=null!=j?j[1]:void 0)&&e.contexts[f]?f:e.defaultContext;c=(g=null!=
j?j[3]:void 0)&&"/"!==g.substr(-1)?g:e.contexts[c].defaultPagePath;var m,b,h,p;g={};if(j=null!=j?j[5]:void 0){h=j.split("&");for(j=0,f=h.length;j<f;j++)m=h[j],p=m.split("="),m=p[0],b=p[1],g[m]=decodeURIComponent(b)}return{hash:a,context:n,page:c,data:g}},current:new j(c(f.get())),canBack:function(){var a;return 1<(null!=(a=m[g.current.context])?a.length:void 0)},goBack:function(){var a;a=m[g.current.context];if(1<a.length)return n=a[1],f.set(n.hash)},goTo:function(a){return f.set(""+g.current.context+
"!"+a)},switchContext:function(a){var c;if("string"===typeof a&&(c=m[a])&&g.current.context!==a)return f.set(q(c[0]||{context:a,page:e.contexts[a].defaultPage}))}});window.ctxHists=m={};for(a in e.contexts)m[a]=[];m[g.current.context].push(g.current);g.bind({"change:current":function(a){var c,f,e;c={};for(f in a)e=a[f],c[f]=e;c.type="change:current[context="+a.cur.context+"]";return g.trigger(c)}});f.onChange(function(){var a,c,e,k;c=new j(g.parseHash(f.get()));a=m[c.context];if(g.current.context!==
c.context)return n=void 0,g.set({current:c},{isBack:!1,isContextSwitch:!0});if(n){for(e=0;a[e].hash!==n.hash;)++e;c=n;n=void 0;a.splice(0,e);return g.set({current:c},{isBack:!0,isContextSwitch:!1})}if(c.hash===(null!=(e=a[1])?e.hash:void 0))return n=void 0,a.splice(0,1),g.set({current:c},{isBack:!0,isContextSwitch:!1});if(1>a.length||(null!=(k=a[0])?k.hash:void 0)!==c.hash)return n=void 0,a.unshift(c),g.set({current:c},{isBack:!1,isContextSwitch:!1})});return g});
var __hasProp=Object.prototype.hasOwnProperty,__extends=function(e,f){function j(){this.constructor=e}for(var g in f)__hasProp.call(f,g)&&(e[g]=f[g]);j.prototype=f.prototype;e.prototype=new j;e.__super__=f.prototype;return e};
define("framework/ContextModel",["./Model"],function(e){return function(){function f(j){var g,m,a,k,c,q=this;a=j.id;k=j.initialHash;m=j.hashManager;j=j.defaultPagePath;f.__super__.constructor.call(this,{id:a,defaultPagePath:j,currentPageModel:g=new e(k),pageHistory:c=[g]});(g={})["change:current[context="+a+"]"]=function(a){var d,f;d=a.cur;a=a.prev;if(!(a=d.context!==(null!=a?a.context:void 0)))(null!=(f=c[1])?f.hash:void 0)===d.hash?c.splice(0,1):c.unshift(new e(d));return q.set({currentPageModel:c[0]},
{isContextSwitch:a})};m.bind(g)}__extends(f,e);return f}()});
define("framework/Context",["require","./Model","./Nav","cell!./Page"],function(e,f,j,g){return{tag:function(){return"<div data-ctxid='"+this.options.contextid+"'>"},afterRender:function(){var e,a,k,c,q;q={};k=null;e=this.$el;a={};c=a["change:current[context="+this.options.contextid+"]"]=function(a){var d,c,j,r,v;d=a.cur;j=a.prev;c=a.data,a=c.isBack;c=q[d.hash];if(r=j&&q[j.hash])delete q[j.hash],r.$el.bind("webkitAnimationEnd",function(){return r.$el.remove()});c||(c=q[d.hash]=new g({model:new f(d)}));
c.$el.prependTo(e);d="Page animate "+((null!=j?j.context:void 0)===d.context?(v=a&&"-reverse"||"",null!=k&&k.$el.attr("class","Page animate headingOut"+v),null!=k&&k.model.trigger("deactivate"),"headingIn"+v):"fadeIn");c.$el.attr("class",d);return(k=c).model.trigger({type:"activate",isback:a})};j.bind(a);return c({cur:this.options.initialHash,data:{isBack:!1}})}}});
define("framework/Page",["require","./Nav"],function(e,f){return{tag:function(){return"<div data-cellpath='"+this.model.page+"'>"},render:function(f){var g=this;return e(["cell!"+this.model.page],function(e){g.$el.append(f(e,{model:g.model}));return g.pageRendered()})},pageRendered:function(){var f,e,m=this;f=!0;this.model.bind({deactivate:function(){return f=!1}});this.model.bind({activate:function(){f=!0;return m.$el.css("visibility","visible")}});this.$el.bind("webkitAnimationEnd",function(){if(!f)return m.$el.css("visibility",
"hidden")});e=new iScroll(this.el);return this.model.bindAndCall({refreshScroller:function(){return e.refresh()}})},on:{"click *[data-navto]":function(e){return f.goTo($(e.target).closest("[data-navto]").data("navto"))}}}});require(["cell"],function(e){e.__preinstalledCells__={"framework/App":0,"pages/schedule/Schedule":0,"shared/ListView":0,"framework/Context":0,"framework/ContextNavBar":0,"framework/Page":0,"framework/TitleBar":0}});var hideAddressBar,ua;document.addEventListener("touchmove",function(e){return e.preventDefault()});
hideAddressBar=function(){var e,f;e=0;setTimeout(f=function(){if(1===++e)return window.scrollTo(0,1)},500);return $(window).bind("resize",function(){e=0;return f()})};$("body").attr("class",(ua=navigator.userAgent).match(/iPhone/i)||ua.match(/iPod/i)||ua.match(/iPad/i)?window.navigator.standalone?"IOSFullScreen":(hideAddressBar(),"IOS"):(hideAddressBar(),"ANDROID"));
define("framework/App","./Nav,./Model,./ContextModel,cell!./Context,cell!./ContextNavBar,cell!./TitleBar".split(","),function(e,f,j,g,m,a){var k;k={};return{render:function(c){return[c(a),c("#content"),c(m)]},afterRender:function(){var a,f=this;a=this.$("#content");return e.bindAndCall({"change:current":function(e){var d,i,j;d=e.cur;i=e.prev;e=e.data;if(!e||null!=e&&e.isContextSwitch){if(!(e=k[d.context]))e=k[d.context]=new g({contextid:d.context,initialHash:d}),a.append(e.$el);e.$el.toggle(!0);if(i=
null!=i?i.context:void 0)null!=(j=k[i])&&j.$el.toggle(!1);e?(f.$("#content > .activeTab").removeClass("activeTab"),e.$el.toggle(!0).toggleClass("activeTab",!0)):"undefined"!==typeof console&&null!==console&&"function"===typeof console.log&&console.log("Could not switch to context = '"+d.context+"'")}}})}}});
define("framework/ContextNavBar",["AppConfig","./Nav"],function(e,f){return{tag:"<ul>",render:function(f){var g,m,a,k;a=e.contexts;k=[];for(g in a)m=a[g].text,k.push(f("<li data-ctxid='"+g+"'>",m||g));return[k]},on:{"click li":function(e){e=e.target;$("li.active").removeClass("active");return f.switchContext($(e).addClass("active").data("ctxid"))}}}});
define("framework/TitleBar",["framework/Nav"],function(e){return{render:function(e){return[e("#backbutton",e("span","Back")),e("#titles",e("#title"),e("#prevtitle")),e("#gobutton",e("span","Do It"))]},afterRender:function(){var f,j,g,m;m=!1;f=this.$("#backbutton");this.$("#backbutton > span");g=this.$("#title");j=this.$("#prevtitle");g.bind("webkitAnimationEnd",function(){g.attr("class","");j.attr("class","");return m=!1});return e.bindAndCall({"change:current.title":function(a){var k,c;k=a.cur;c=
a.prev;a=a.data;a=null!=a?a.isBack:void 0;g.html(k||"");if(!m)return f.css("visibility",e.canBack()&&"visible"||"hidden"),k=a&&"-reverse"||"",c&&j.html(c).attr("class","animate headingOutFade"+k),g.attr("class","animate headingInFade"+k),m=!0}})},on:{"click #backbutton":function(){return e.goBack()}}}});
